export const OBTER_PROJETOS = "OBTER_PROJETO";
export const CADASTRAR_PROJETOS = "CADASTRAR_PROJETO";
export const ALTERAR_PROJETOS = "ALTERAR_PROJETO";
export const REMOVER_PROJETOS = "REMOVER_PROJETO";
export const OBTER_TAREFAS = "OBTER_TAREFAS";
export const CADASTRAR_TAREFA = "CADASTRAR_TAREFA";
export const ALTERAR_TAREFA = "ALTERAR_TAREFA";
